version: '3'
name: "thelounge"
services:
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ~/data/thelounge:/var/opt/thelounge # bind lounge config from the host's file system
