version: '3'
name: "wallabag"
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - SYMFONY__ENV__FROM_EMAIL=wallabag@pascalj.de
      - SYMFONY__ENV__DOMAIN_NAME=https://read.pascalj.de
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    ports:
      - 8557:80
    volumes:
      - ~/data/wallabag/images:/var/www/wallabag/web/assets/images
      - ~/data/wallabag/wallabag:/var/www/wallabag/data
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    restart: unless-stopped
